# Generated by Django 4.1.7 on 2023-06-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealKitsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='recipies',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealKitsApp.cart')),
                ('recipies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealKitsApp.recipe')),
            ],
        ),
    ]
