# Generated by Django 4.1.7 on 2023-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealKitsApp', '0003_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
