# Generated by Django 4.1.7 on 2023-06-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealKitsApp', '0012_rename_recipies_cartitem_recipe_remove_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='qty',
        ),
        migrations.CreateModel(
            name='ProductPortions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MealKitsApp.recipe')),
            ],
        ),
    ]
