# Generated by Django 4.1.7 on 2023-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealKitsApp', '0015_recipe_qty_delete_productportions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='qty',
        ),
    ]
