# Generated by Django 4.1.7 on 2023-06-28 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealKitsApp', '0016_remove_recipe_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_time_end',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_time_start',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=12)),
                ('name_on_card', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MealKitsApp.buyer')),
            ],
        ),
    ]
